### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by himaniyadav** [quinngroup/parkinsons_multimodal#2]
CUDA keeps running out of memory as soon as I try to start training the VAE. Pretty sure it's because of the size of the network and not the input data -- should I just start by getting rid of some of the layers to try to reduce the network?

Here's the output from main.py and error trace, including a summary of the network showing its size:
```

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
_VAE_NN                                  --                        --
├─Sequential: 1-1                        [1, 1024, 1, 1, 1]        --
│    └─DoubleConv: 2-1                   [1, 64, 193, 229, 193]    --
│    │    └─Sequential: 3-1              [1, 64, 193, 229, 193]    112,704
│    └─Downsample: 2-2                   [1, 64, 96, 114, 96]      --
│    │    └─MaxPool3d: 3-2               [1, 64, 96, 114, 96]      --
│    └─DoubleConv: 2-3                   [1, 128, 96, 114, 96]     --
│    │    └─Sequential: 3-3              [1, 128, 96, 114, 96]     664,320
│    └─Downsample: 2-4                   [1, 128, 48, 57, 48]      --
│    │    └─MaxPool3d: 3-4               [1, 128, 48, 57, 48]      --
│    └─DoubleConv: 2-5                   [1, 256, 48, 57, 48]      --
│    │    └─Sequential: 3-5              [1, 256, 48, 57, 48]      2,655,744
│    └─Downsample: 2-6                   [1, 256, 24, 28, 24]      --
│    │    └─MaxPool3d: 3-6               [1, 256, 24, 28, 24]      --
│    └─DoubleConv: 2-7                   [1, 512, 24, 28, 24]      --
│    │    └─Sequential: 3-7              [1, 512, 24, 28, 24]      10,619,904
│    └─Downsample: 2-8                   [1, 512, 12, 14, 12]      --
│    │    └─MaxPool3d: 3-8               [1, 512, 12, 14, 12]      --
│    └─Downsample: 2-9                   [1, 512, 6, 7, 6]         --
│    │    └─MaxPool3d: 3-9               [1, 512, 6, 7, 6]         --
│    └─DoubleConv: 2-10                  [1, 1024, 6, 7, 6]        --
│    │    └─Sequential: 3-10             [1, 1024, 6, 7, 6]        42,473,472
│    └─Downsample: 2-11                  [1, 1024, 3, 3, 3]        --
│    │    └─MaxPool3d: 3-11              [1, 1024, 3, 3, 3]        --
│    └─Downsample: 2-12                  [1, 1024, 1, 1, 1]        --
│    │    └─MaxPool3d: 3-12              [1, 1024, 1, 1, 1]        --
├─FC: 1-2                                [1, 256]                  --
│    └─Sequential: 2-13                  [1, 256]                  --
│    │    └─Linear: 3-13                 [1, 256]                  262,400
│    │    └─ReLU: 3-14                   [1, 256]                  --
│    │    └─Dropout: 3-15                [1, 256]                  --
├─FC: 1-3                                [1, 256]                  --
│    └─Sequential: 2-14                  [1, 256]                  --
│    │    └─Linear: 3-16                 [1, 256]                  262,400
│    │    └─ReLU: 3-17                   [1, 256]                  --
│    │    └─Dropout: 3-18                [1, 256]                  --
├─FC: 1-4                                [1, 1024]                 --
│    └─Sequential: 2-15                  [1, 1024]                 --
│    │    └─Linear: 3-19                 [1, 1024]                 263,168
│    │    └─ReLU: 3-20                   [1, 1024]                 --
│    │    └─Dropout: 3-21                [1, 1024]                 --
├─Sequential: 1-5                        [1, 1, 193, 229, 193]     --
│    └─Upsample: 2-16                    [1, 1024, 2, 2, 2]        --
│    │    └─ConvTranspose3d: 3-22        [1, 1024, 2, 2, 2]        8,389,632
│    └─Upsample: 2-17                    [1, 1024, 4, 4, 4]        --
│    │    └─ConvTranspose3d: 3-23        [1, 1024, 4, 4, 4]        8,389,632
│    └─DoubleConv: 2-18                  [1, 512, 4, 4, 4]         --
│    │    └─Sequential: 3-24             [1, 512, 4, 4, 4]         21,236,736
│    └─Upsample: 2-19                    [1, 512, 8, 8, 8]         --
│    │    └─ConvTranspose3d: 3-25        [1, 512, 8, 8, 8]         2,097,664
│    └─Upsample: 2-20                    [1, 512, 16, 16, 16]      --
│    │    └─ConvTranspose3d: 3-26        [1, 512, 16, 16, 16]      2,097,664
│    └─DoubleConv: 2-21                  [1, 256, 16, 16, 16]      --
│    │    └─Sequential: 3-27             [1, 256, 16, 16, 16]      5,309,952
│    └─Upsample: 2-22                    [1, 256, 32, 32, 32]      --
│    │    └─ConvTranspose3d: 3-28        [1, 256, 32, 32, 32]      524,544
│    └─DoubleConv: 2-23                  [1, 128, 32, 32, 32]      --
│    │    └─Sequential: 3-29             [1, 128, 32, 32, 32]      1,327,872
│    └─Upsample: 2-24                    [1, 128, 64, 64, 64]      --
│    │    └─ConvTranspose3d: 3-30        [1, 128, 64, 64, 64]      131,200
│    └─DoubleConv: 2-25                  [1, 64, 64, 64, 64]       --
│    │    └─Sequential: 3-31             [1, 64, 64, 64, 64]       332,160
│    └─Upsample: 2-26                    [1, 64, 128, 128, 128]    --
│    │    └─ConvTranspose3d: 3-32        [1, 64, 128, 128, 128]    32,832
│    └─DoubleConv: 2-27                  [1, 1, 128, 128, 128]     --
│    │    └─Sequential: 3-33             [1, 1, 128, 128, 128]     1,761
│    └─OutputUpsample: 2-28              [1, 1, 193, 229, 193]     --
│    │    └─ConvTranspose3d: 3-34        [1, 1, 193, 229, 193]     9
==========================================================================================
Total params: 107,185,770
Trainable params: 107,185,770
Non-trainable params: 0
Total mult-adds (T): 2.48
==========================================================================================
Input size (MB): 34.12
Forward/backward pass size (MB): 25390.98
Params size (MB): 428.74
Estimated Total Size (MB): 25853.84
==========================================================================================
[INFO] Beginning VAE training
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    vae.train(data, args['epochs'], save_frequency=args['save_frequency'])
  File "/home/himani/parkinsons_multimodal/src/Models/VAE.py", line 149, in train
    reconstructed_batch, mu, logvar = self.model(batch.float())
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/himani/parkinsons_multimodal/src/Models/VAE.py", line 70, in forward
    x = self.encoder_convolutions(x)
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/himani/parkinsons_multimodal/src/Models/VAE_pieces.py", line 48, in forward
    return self.double_conv(x)
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 587, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/himani/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 583, in _conv_forward
    input, weight, bias, self.stride, self.padding, self.dilation, self.groups
RuntimeError: CUDA out of memory. Tried to allocate 514.00 MiB (GPU 0; 11.91 GiB total capacity; 10.73 GiB already allocated; 106.94 MiB free; 11.06 GiB reserved in total by PyTorch)

```

**Comment by Micky774** [comment]
~~What batch-size are you running this with?~~ Actually never mind, the network is far too large even for a batch-size of 1.

**Comment by Micky774** [comment]
You definitely need to reduce computational complexity. I would recommend spatial broadcast decoding over transpose convolutions for _most_ tasks. See: https://arxiv.org/pdf/1901.07017.pdf

We also have a coded implementation of this in a couple different spots. See: https://github.com/quinngroup/metric-vae/blob/a3bd92262ddff633dcb303afca6a4c22005419a5/utils/models.py#L90-L110

A more generic utils implementation here: https://github.com/quinngroup/CiliaRepresentation/blob/e1f80399818c2edc7a788a3194da42d9c5cd3e8f/VTP/utils/nn.py#L78-L105

**Comment by Micky774** [comment]
Another way you can reduce the complexity is by capping feature-map depth to 512 rather than going to 1024 -- that's a massive amount of features and with a small bottleneck (as should be the goal with a VAE) it isn't really necessary. Also look into depth-wise separable convolutions.

**Comment by Micky774** [comment]
Furthermore this would be a wonderful use-case for applying PyTorch's model-parallelism for distribution over multiple GPUs. In fact, implementing it smartly would make it so you _barely_ have to reduce model complexity at all to get it to run. I would still recommend implementing model-parallelism in tandem with the other suggestions, but this is definitely one of the most potent things you can do to help.

See: https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html

**Comment by himaniyadav** [comment]
Yep it's a batch size of one. Thank you for the suggestions; I'll look into everything, especially the model-parallelism.

**Comment by himaniyadav** [comment]
Just to recap on my progress with some of these complexity-reducing measures: capping feature-map depth at 512 significantly reduced the parameters (~100 million to 25 million), but didn't seem to affect the forward/backward pass size enough to make a difference in the overall size of the model. 

```
==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
_VAE_NN                                  --                        --
├─Sequential: 1-1                        [1, 512, 1, 1, 1]         --
│    └─DoubleConv: 2-1                   [1, 64, 193, 229, 193]    --
│    │    └─Sequential: 3-1              [1, 64, 193, 229, 193]    112,704
│    └─Downsample: 2-2                   [1, 64, 96, 114, 96]      --
│    │    └─MaxPool3d: 3-2               [1, 64, 96, 114, 96]      --
│    └─DoubleConv: 2-3                   [1, 128, 96, 114, 96]     --
│    │    └─Sequential: 3-3              [1, 128, 96, 114, 96]     664,320
│    └─Downsample: 2-4                   [1, 128, 48, 57, 48]      --
│    │    └─MaxPool3d: 3-4               [1, 128, 48, 57, 48]      --
│    └─DoubleConv: 2-5                   [1, 256, 48, 57, 48]      --
│    │    └─Sequential: 3-5              [1, 256, 48, 57, 48]      2,655,744
│    └─Downsample: 2-6                   [1, 256, 24, 28, 24]      --
│    │    └─MaxPool3d: 3-6               [1, 256, 24, 28, 24]      --
│    └─DoubleConv: 2-7                   [1, 512, 24, 28, 24]      --
│    │    └─Sequential: 3-7              [1, 512, 24, 28, 24]      10,619,904
│    └─Downsample: 2-8                   [1, 512, 12, 14, 12]      --
│    │    └─MaxPool3d: 3-8               [1, 512, 12, 14, 12]      --
│    └─Downsample: 2-9                   [1, 512, 6, 7, 6]         --
│    │    └─MaxPool3d: 3-9               [1, 512, 6, 7, 6]         --
│    └─Downsample: 2-10                  [1, 512, 3, 3, 3]         --
│    │    └─MaxPool3d: 3-10              [1, 512, 3, 3, 3]         --
│    └─Downsample: 2-11                  [1, 512, 1, 1, 1]         --
│    │    └─MaxPool3d: 3-11              [1, 512, 1, 1, 1]         --
├─FC: 1-2                                [1, 256]                  --
│    └─Sequential: 2-12                  [1, 256]                  --
│    │    └─Linear: 3-12                 [1, 256]                  131,328
│    │    └─ReLU: 3-13                   [1, 256]                  --
│    │    └─Dropout: 3-14                [1, 256]                  --
├─FC: 1-3                                [1, 256]                  --
│    └─Sequential: 2-13                  [1, 256]                  --
│    │    └─Linear: 3-15                 [1, 256]                  131,328
│    │    └─ReLU: 3-16                   [1, 256]                  --
│    │    └─Dropout: 3-17                [1, 256]                  --
├─FC: 1-4                                [1, 512]                  --
│    └─Sequential: 2-14                  [1, 512]                  --
│    │    └─Linear: 3-18                 [1, 512]                  131,584
│    │    └─ReLU: 3-19                   [1, 512]                  --
│    │    └─Dropout: 3-20                [1, 512]                  --
├─Sequential: 1-5                        [1, 1, 1, 37, 1]          --
│    └─Upsample: 2-15                    [1, 512, 2, 2, 2]         --
│    │    └─ConvTranspose3d: 3-21        [1, 512, 2, 2, 2]         2,097,664
│    └─Upsample: 2-16                    [1, 512, 4, 4, 4]         --
│    │    └─ConvTranspose3d: 3-22        [1, 512, 4, 4, 4]         2,097,664
│    └─DoubleConv: 2-17                  [1, 256, 4, 4, 4]         --
│    │    └─Sequential: 3-23             [1, 256, 4, 4, 4]         5,309,952
│    └─Upsample: 2-18                    [1, 256, 8, 8, 8]         --
│    │    └─ConvTranspose3d: 3-24        [1, 256, 8, 8, 8]         524,544
│    └─DoubleConv: 2-19                  [1, 128, 8, 8, 8]         --
│    │    └─Sequential: 3-25             [1, 128, 8, 8, 8]         1,327,872
│    └─Upsample: 2-20                    [1, 128, 16, 16, 16]      --
│    │    └─ConvTranspose3d: 3-26        [1, 128, 16, 16, 16]      131,200
│    └─DoubleConv: 2-21                  [1, 64, 16, 16, 16]       --
│    │    └─Sequential: 3-27             [1, 64, 16, 16, 16]       332,160
│    └─Upsample: 2-22                    [1, 64, 32, 32, 32]       --
│    │    └─ConvTranspose3d: 3-28        [1, 64, 32, 32, 32]       32,832
│    └─DoubleConv: 2-23                  [1, 1, 32, 32, 32]        --
│    │    └─Sequential: 3-29             [1, 1, 32, 32, 32]        1,761
│    └─OutputUpsample: 2-24              [1, 1, 1, 37, 1]          --
│    │    └─ConvTranspose3d: 3-30        [1, 1, 1, 37, 1]          9
==========================================================================================
Total params: 26,302,570
Trainable params: 26,302,570
Non-trainable params: 0
Total mult-adds (T): 2.18
==========================================================================================
Input size (MB): 34.12
Forward/backward pass size (MB): 23147.30
Params size (MB): 105.21
Estimated Total Size (MB): 23286.63
==========================================================================================
...
RuntimeError: CUDA out of memory. Tried to allocate 514.00 MiB (GPU 0; 11.91 GiB total capacity; 10.62 GiB already allocated; 212.94 MiB free; 10.95 GiB reserved in total by PyTorch)
```

Then I started the process of implementing spatial broadcast decoding, and got rid of the existing decoder while testing that. I noticed that even with no decoder, the same memory issue came up -- so while spatial broadcast decoding would be helpful in decreasing the complexity of the decoder, the encoder is still too big. I'll still work on finishing the implementation of spatial broadcast decoding, but worth noting that on its own it definitely won't be enough. The model summary and ensuing error message is shown below:

```
==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
_VAE_NN                                  --                        --
├─Sequential: 1-1                        [1, 512, 1, 1, 1]         --
│    └─DoubleConv: 2-1                   [1, 64, 193, 229, 193]    --
│    │    └─Sequential: 3-1              [1, 64, 193, 229, 193]    112,704
│    └─Downsample: 2-2                   [1, 64, 96, 114, 96]      --
│    │    └─MaxPool3d: 3-2               [1, 64, 96, 114, 96]      --
│    └─DoubleConv: 2-3                   [1, 128, 96, 114, 96]     --
│    │    └─Sequential: 3-3              [1, 128, 96, 114, 96]     664,320
│    └─Downsample: 2-4                   [1, 128, 48, 57, 48]      --
│    │    └─MaxPool3d: 3-4               [1, 128, 48, 57, 48]      --
│    └─DoubleConv: 2-5                   [1, 256, 48, 57, 48]      --
│    │    └─Sequential: 3-5              [1, 256, 48, 57, 48]      2,655,744
│    └─Downsample: 2-6                   [1, 256, 24, 28, 24]      --
│    │    └─MaxPool3d: 3-6               [1, 256, 24, 28, 24]      --
│    └─DoubleConv: 2-7                   [1, 512, 24, 28, 24]      --
│    │    └─Sequential: 3-7              [1, 512, 24, 28, 24]      10,619,904
│    └─Downsample: 2-8                   [1, 512, 12, 14, 12]      --
│    │    └─MaxPool3d: 3-8               [1, 512, 12, 14, 12]      --
│    └─Downsample: 2-9                   [1, 512, 6, 7, 6]         --
│    │    └─MaxPool3d: 3-9               [1, 512, 6, 7, 6]         --
│    └─Downsample: 2-10                  [1, 512, 3, 3, 3]         --
│    │    └─MaxPool3d: 3-10              [1, 512, 3, 3, 3]         --
│    └─Downsample: 2-11                  [1, 512, 1, 1, 1]         --
│    │    └─MaxPool3d: 3-11              [1, 512, 1, 1, 1]         --
├─FC: 1-2                                [1, 256]                  --
│    └─Sequential: 2-12                  [1, 256]                  --
│    │    └─Linear: 3-12                 [1, 256]                  131,328
│    │    └─ReLU: 3-13                   [1, 256]                  --
│    │    └─Dropout: 3-14                [1, 256]                  --
├─FC: 1-3                                [1, 256]                  --
│    └─Sequential: 2-13                  [1, 256]                  --
│    │    └─Linear: 3-15                 [1, 256]                  131,328
│    │    └─ReLU: 3-16                   [1, 256]                  --
│    │    └─Dropout: 3-17                [1, 256]                  --
├─SpatialBroadcastDecoder: 1-4           [1, 256]                  --
==========================================================================================
Total params: 14,315,328
Trainable params: 14,315,328
Non-trainable params: 0
Total mult-adds (T): 2.18
==========================================================================================
Input size (MB): 34.12
Forward/backward pass size (MB): 23112.92
Params size (MB): 57.26
Estimated Total Size (MB): 23204.30
==========================================================================================
[INFO] Beginning VAE training
...
RuntimeError: CUDA out of memory. Tried to allocate 514.00 MiB (GPU 0; 11.91 GiB total capacity; 10.53 GiB already allocated; 304.94 MiB free; 10.86 GiB reserved in total by PyTorch)
```

I will start implementing the model-parallelism which will hopefully help more, but just wanted to note that the first two suggestions don't seem to be useful on their own.

**Comment by himaniyadav** [comment]
It looks like no matter what we do, the 514MiB number isn't affected by how many parameters we reduce. I did start on the model-parallelism, trying to split up the encoder onto a couple GPUs since we determined that alone might be too big,  (it's not really the best implementation, more a test to see if it would work), but since the 514MB isn't changing I'm not sure how much that would be affected by model parallelism either. Is there something else I'm missing?

```
[INFO] Device detected: cuda
==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
_VAE_NN                                  --                        --
├─Sequential: 1-1                        [1, 512, 1, 1, 1]         --
│    └─DoubleConv: 2-1                   [1, 64, 193, 229, 193]    --
│    │    └─Sequential: 3-1              [1, 64, 193, 229, 193]    112,704
│    └─Downsample: 2-2                   [1, 64, 96, 114, 96]      --
│    │    └─MaxPool3d: 3-2               [1, 64, 96, 114, 96]      --
│    └─DoubleConv: 2-3                   [1, 128, 96, 114, 96]     --
│    │    └─Sequential: 3-3              [1, 128, 96, 114, 96]     664,320
│    └─Downsample: 2-4                   [1, 128, 48, 57, 48]      --
│    │    └─MaxPool3d: 3-4               [1, 128, 48, 57, 48]      --
│    └─DoubleConv: 2-5                   [1, 256, 48, 57, 48]      --
│    │    └─Sequential: 3-5              [1, 256, 48, 57, 48]      2,655,744
│    └─Downsample: 2-6                   [1, 256, 24, 28, 24]      --
│    │    └─MaxPool3d: 3-6               [1, 256, 24, 28, 24]      --
│    └─DoubleConv: 2-7                   [1, 512, 24, 28, 24]      --
│    │    └─Sequential: 3-7              [1, 512, 24, 28, 24]      10,619,904
│    └─Downsample: 2-8                   [1, 512, 12, 14, 12]      --
│    │    └─MaxPool3d: 3-8               [1, 512, 12, 14, 12]      --
│    └─Downsample: 2-9                   [1, 512, 6, 7, 6]         --
│    │    └─MaxPool3d: 3-9               [1, 512, 6, 7, 6]         --
│    └─Downsample: 2-10                  [1, 512, 3, 3, 3]         --
│    │    └─MaxPool3d: 3-10              [1, 512, 3, 3, 3]         --
│    └─Downsample: 2-11                  [1, 512, 1, 1, 1]         --
│    │    └─MaxPool3d: 3-11              [1, 512, 1, 1, 1]         --
├─FC: 1-2                                [1, 256]                  --
│    └─Sequential: 2-12                  [1, 256]                  --
│    │    └─Linear: 3-12                 [1, 256]                  131,328
│    │    └─ReLU: 3-13                   [1, 256]                  --
│    │    └─Dropout: 3-14                [1, 256]                  --
├─FC: 1-3                                [1, 256]                  --
│    └─Sequential: 2-13                  [1, 256]                  --
│    │    └─Linear: 3-15                 [1, 256]                  131,328
│    │    └─ReLU: 3-16                   [1, 256]                  --
│    │    └─Dropout: 3-17                [1, 256]                  --
==========================================================================================
Total params: 14,315,328
Trainable params: 14,315,328
Non-trainable params: 0
Total mult-adds (T): 2.18
==========================================================================================
Input size (MB): 34.12
Forward/backward pass size (MB): 23112.92
Params size (MB): 57.26
Estimated Total Size (MB): 23204.30
==========================================================================================
[INFO] Beginning VAE training
...
RuntimeError: CUDA out of memory. Tried to allocate 514.00 MiB (GPU 0; 11.91 GiB total capacity; 10.62 GiB already allocated; 212.94 MiB free; 10.95 GiB reserved in total by PyTorch)
```

**Comment by Micky774** [comment]
Where is the most recent version of your code? Is it in a separate branch, or in the `main` branch?

**Comment by himaniyadav** [comment]
It's in main

**Comment by Micky774** [comment]
when trying to run, I get `FileNotFoundError: [Errno 2] No such file or directory: 'data_info.csv'`

**Comment by Micky774** [comment]
Also, no matter what you do the 514MiB number won't change because that's not the problem, nor is it what we're trying to change. We're trying to optimize `Estimated Total Size (MB): 23204.30`, which started out as `25853.84`. The majority of the complexity lies in the encoder, so drastic down-sampling _before_ encoding should help a bit. That is, move two down-sample operations before even the first convolution layer

The 514MiB is just the size of one, arbitrary chunk that Pytorch is trying to load in. The problem is that it can't be loaded, because the GPU is full. The GPU is full because of the _rest_ of the `23204.30MB` trying to fit in it.

**Comment by himaniyadav** [comment]
Oh, for the first run I think you need to uncomment line 24 in main.py `#add_path_to_tsv(tsv_path)` -- sorry the code isn't super clear in that aspect!

**Comment by Micky774** [comment]
Could you also make a `requirements.txt` for this project? There are several imports I'm lacking, and rather than try to fix them 1-by-1 it would be nice to have it all in one place. This is also just generally good practice for reproducibility in code.

**Comment by himaniyadav** [comment]
Okay, will do when I get a chance! 

Your tip of moving a couple downsampling operations before the convolution layer worked so the model finally trains! I'll work on the other stuff like spatial broadcast decoding still, but this specific issue is resolved.
